name: travelbot-group

services:
  postgres:
    image: postgres:17.9-alpine3.23
    container_name: travelbot-db
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: travelbot
    ports:
      - "5432:5432"
    volumes:
      - travelbot_pgdata:/var/lib/postgresql/data

volumes:
  travelbot_pgdata:
